server:
  port : 9090 
  servlet:
    context-path: /admin-backend
spring:
  application:
    name: admin-backend
  profiles:
    active: @spring.profiles.active@
  cloud:
    config:
      enabled: true
      label: latest
  config:
    import: optional:configserver:http://config-server:8888/config-server
  jackson:
    property-naming-strategy: SNAKE_CASE
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/1_dev.xml
